CC=g++
CFLAGS=-c -O3 -march=native -std=c++11 -msse4.1
LDFLAGS=-lpthread
SOURCES=main_mnist.cpp reader.cpp convolution_layer/convolution.cpp convolution_layer/lowp.cpp pooling_layer/pooling.cpp fully_connected_layer/fully_connected.cpp relu_layer/relu.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=lpa_cnn.out

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
